# Generated by Django 3.2.8 on 2021-10-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_carmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='artist',
            new_name='make',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
